language: elm

install:
  - npm install -g create-elm-app@3.0.6

script:
  - elm-app build
  - mv ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: elm-countdown.surge.sh
  skip_cleanup: true